name: ecommerce
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  razorpay_flutter: ^1.3.5
  stripe_payment: ^1.0.2
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
url_launcher: ^6.0.10
razorpay_flutter: ^1.2.6
  



flutter:
  uses-material-design: true
  assets:
    - assets/products/
  